### ISSUE TITLE
Crash on reaching end of device

### ISSUE THREAD

**Issue by JagerSprinkles** [The-Fortress-of-Brolitude/wipedicks#3]
I used this script to directly write to a device.
It seems to hit an out of space error at the end of the device once it's filled the device.
I even supplied the -n 3 flag to have it do multiple passes but it crashed at the end and did not start another pass automatically.

OS: Debian 10.2
Python3.7

![Screenshot_20191124-105906__01](https://user-images.githubusercontent.com/6476475/69497397-94afcd80-0eaa-11ea-830c-0acc1f4547e3.jpg)

**Comment by Drewsif** [comment]
Thanks for the bug report!

**Comment by JagerSprinkles** [comment]
I just used this script again and ran into the same error, just a heads up. I can provide addition details if needed, would just need to know what information to send.
